#!/usr/bin/env node

logger      = require('winston');
logger.add(logger.transports.File, { filename: '/var/log/raspi-printer.log', json:false });

PrintQueue  = require("./lib/print-queue").PrintQueue
PrintServer = require("./lib/print-server.js").PrintServer
PrinterId   = require("./lib/printer-id.js").PrinterId
Printer     = require("./lib/printer.js").Printer
Ui          = require("./lib/ui").Ui

PrinterController = require("./lib/printer-controller.js").PrinterController

PrinterId.logger = logger;
Printer

config = {
  type   : 'A2-raw',
  server : 'http://printer.gofreerange.com:80/printer/' + PrinterId.get()
}

logger.info("Printer URL: ", config.server);

controller = new PrinterController({
                    printServer: new PrintServer(config.server, config.type, { logger: logger }), 
                    printQueue: new PrintQueue({ logger: logger }),
                    ui: new Ui({ logger: logger }),
                    printer: new Printer('/dev/ttyAMA0', { logger: logger }),
                    logger: logger
                  })
